version: "3.7"

services:
  iu-redis-single:
    restart: always
    container_name: iu-redis-single
    image: redis
    ports:
      - 6379:6379

  # iu-redis:
  #   restart: always
  #   container_name: iu-redis
  #   image: grokzen/redis-cluster
  #   ##     environment:
  #   ##       - REDIS_CLUSTER_IP=0.0.0.0
  #   ##       - IP=0.0.0.0
  #   ports:
  #     - 7000-7005:7000-7005
